"""Add tournament table

Revision ID: e3f2c415d9f6
Revises: 
Create Date: 2025-10-01 01:10:03.313865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f2c415d9f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('session_start', sa.DATETIME(), nullable=True),
    sa.Column('session_end', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
